name: R-CMD-check (renv)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  R-CMD-check:
    name: R CMD check on ${{ matrix.config }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ["r-release", "r-oldrel"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # use the R version alias from the matrix
          r-version: ${{ matrix.config }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libxml2-dev libssl-dev libcurl4-openssl-dev

      - name: Cache renv cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install renv and restore packages
        run: |
          Rscript -e "install.packages('renv', repos='https://cloud.r-project.org')"
          Rscript -e "renv::restore(lockfile = 'renv.lock', confirm = FALSE)"

      - name: Run package tests
        run: |
          Rscript -e "if (!requireNamespace('testthat', quietly=TRUE)) install.packages('testthat', repos='https://cloud.r-project.org')"
          Rscript -e "devtools::test()"

      - name: Build package tarball
        run: |
          Rscript -e "if (!requireNamespace('devtools', quietly=TRUE)) install.packages('devtools', repos='https://cloud.r-project.org')"
          R CMD build --no-build-vignettes .

      - name: Run R CMD check
        run: |
          # Use --no-manual for faster checks on Ubuntu runners
          for pkg in *.tar.gz; do
            R CMD check --no-manual --as-cran "$pkg"
          done
